spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/config-repo/eureka
            - file:/config-repo/gateway
            - file:/config-repo/auth
            - file:/config-repo/diet
