version: "3.9"

networks:
  planifai-net:
    driver: bridge

volumes:
  postgres_auth_data:
  postgres_task_data:
  mongo_data:

services:
  config-server:
    build: ./config/config-server
    networks:
      - planifai-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure

  eureka-server:
    build: ./discovery/eureka-server
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - planifai-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: on-failure

  api-gateway:
    build: ./gateway/api-gateway
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - planifai-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: on-failure

  auth-service:
    build: ./auth/auth-service
    depends_on:
      - eureka-server
      - postgres-auth
    networks:
      - planifai-net

  task-service:
    build: ./tasks/task-service
    depends_on:
      - eureka-server
      - postgres-task
    networks:
      - planifai-net

  diet-service:
    build: ./diet/diet-service
    depends_on:
      - eureka-server
      - postgres-task
    networks:
      - planifai-net

  finance-service:
    build: ./finance/finance-service
    depends_on:
      - eureka-server
      - postgres-task
    networks:
      - planifai-net

  ai-service:
    build: ./ai/ai-service
    networks:
      - planifai-net

  postgres-auth:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - planifai-net

  postgres-task:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${TASK_DB_NAME}
      POSTGRES_USER: ${TASK_DB_USER}
      POSTGRES_PASSWORD: ${TASK_DB_PASSWORD}
    volumes:
      - postgres_task_data:/var/lib/postgresql/data
    networks:
      - planifai-net

  redis:
    image: redis:alpine
    networks:
      - planifai-net

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - planifai-net
