services:
  api-gateway:
    environment:
      SPRING_PROFILES_ACTIVE: prod

  auth-service:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}

  postgres-auth:
    environment:
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
