services:
  config-server:
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE},native
    volumes:
      - ../PlanifAI-config-repo:/config-repo:ro

  eureka-server:
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

  api-gateway:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      JWT_SECRET: ${JWT_SECRET}

  auth-service:
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  postgres-auth:
    ports:
      - "5433:5432"
