services:
  config-server:
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: ${GIT_CONFIG_USERNAME}
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GIT_CONFIG_PASSWORD}

  eureka-server:
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

  api-gateway:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

  auth-service:
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${AUTH_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DB_PASSWORD}

  task-service:
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${TASK_DB_HOST}:${TASK_DB_PORT}/${TASK_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${TASK_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${TASK_DB_PASSWORD}

  diet-service:
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DIET_DB_HOST}:${DIET_DB_PORT}/${DIET_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DIET_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DIET_DB_PASSWORD}

  finance-service:
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${FINANCE_DB_HOST}:${FINANCE_DB_PORT}/${FINANCE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${FINANCE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${FINANCE_DB_PASSWORD}

  ai-service:
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

  postgres-auth:
    ports:
      - "5433:5432"

  postgres-task:
    ports:
      - "5434:5432"

  redis:
    ports:
      - "6379:6379"

  mongodb:
    ports:
      - "27017:27017"
