networks:
  planifai-net:
    driver: bridge

volumes:
  postgres_auth_data:

services:
  api-gateway:
    build: ./gateway/api-gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - planifai-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: on-failure

  auth-service:
    build: ./auth/auth-service
    depends_on:
      postgres-auth:
        condition: service_started
    networks:
      - planifai-net

  postgres-auth:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - planifai-net

