spring:
  application:
    name: config-server

  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: https://github.com/pablobaskes/PlanifAI-config-repo.git
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}

          default-label: main

server:
  port: 8888
