spring:
  profiles: test
  datasource:
    driver-class-name: org.postgresql.Driver

spring.cloud:
  config:
    enabled: false

eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework: WARN
    com.planifAI: DEBUG
